function $(id){return document.getElementById(id)}

const screens={home:$('home'),register:$('register'),movementForm:$('movementForm'),movements:$('movements'),reports:$('reports')};
const screenList=Object.values(screens).filter(Boolean);
let totals=JSON.parse(localStorage.getItem('financial_totals_v1')||'{"income":0,"expense":0}');
let movements=JSON.parse(localStorage.getItem('financial_movements_v1')||'[]');
let digits={income:'',expense:''};
let activeType='income';
let editingIndex=null;
const categories={income:['Nómina','Bizum','Transferencia','Otros'],expense:['Alimentación','Transporte','Vivienda','Ocio','Compras','Salud','Bizum','Transferencia','Otros']};
const personCategories=['Bizum','Transferencia'];
const descriptionCategories=['Otros','Bizum','Transferencia'];

function show(name){screenList.forEach(s=>s.classList.add('hidden'));if(screens[name])screens[name].classList.remove('hidden');const header=$('appHeader');if(header)header.classList.toggle('hidden',name==='register'||name==='movements');window.scrollTo(0,0);if(name==='register')renderRecentMovements();if(name==='movements')renderMovements();if(name==='reports')renderReportMovements()}
function selectRegisterTab(tab){const tabs=document.querySelectorAll('.register-tab');if(!tabs.length)return;const isRegister=tab==='register';tabs.forEach(button=>{const active=button.dataset.tab===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});show(isRegister?'register':'movements')}
function money(n){return `€${Number(n).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function today(){return new Date().toISOString().slice(0,10)}
function renderAmount(){const input=$('activeAmount');if(!input)return;const n=Number(digits[activeType]||0)/100;input.value=n?n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}):''}
function updateReports(){if($('incomeTotal'))$('incomeTotal').textContent=money(totals.income);if($('expenseTotal'))$('expenseTotal').textContent=money(totals.expense);if($('balanceTotal'))$('balanceTotal').textContent=money(totals.income-totals.expense)}
function formatDateTime(m){const d=m.createdAt?new Date(m.createdAt):new Date((m.date||today())+'T00:00:00');return `${d.toLocaleDateString('es-ES')} · ${d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`}
function movementCard(m,index){const originalIndex=movements.indexOf(m);return `<article class="record ${m.type}"><div class="record-main"><div class="record-title"><span class="record-kind">${m.type==='income'?'Ingreso':'Gasto'}</span><strong>${m.type==='income'?'+':'−'}${money(m.amount).slice(1)}</strong></div><div class="record-meta"><span>${m.category||'Sin categoría'}</span><span>${formatDateTime(m)}</span></div>${m.payMonth?`<div class="record-description"><b>Mes de nómina:</b> ${escapeHtml(m.payMonth)}</div>`:''}${m.person?`<div class="record-description"><b>Persona:</b> ${escapeHtml(m.person)}</div>`:''}${m.description?`<div class="record-description">${escapeHtml(m.description)}</div>`:''}</div><div class="record-actions"><button type="button" class="edit-record" data-index="${originalIndex}" aria-label="Editar registro" title="Editar">✎</button><button type="button" class="delete-record" data-index="${originalIndex}" aria-label="Eliminar registro" title="Eliminar">⌫</button></div></article>`}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderRecentMovements(){const list=$('recentMovements'),count=$('recentCount');if(!list)return;const recent=movements.slice().reverse().slice(0,8);if(count)count.textContent=movements.length;if(!recent.length){list.innerHTML='<p class="empty-list">Todavía no hay movimientos registrados.</p>';return}list.innerHTML=recent.map(m=>movementCard(m,movements.indexOf(m))).join('');bindRecordActions(list)}
function renderReportMovements(){const list=$('reportMovements'),count=$('reportCount');if(!list)return;if(count)count.textContent=movements.length;if(!movements.length){list.innerHTML='<p class="empty-list">Todavía no hay movimientos registrados.</p>';return}list.innerHTML=movements.slice().reverse().map(m=>movementCard(m,movements.indexOf(m))).join('');bindRecordActions(list)}
function renderMovements(){const list=$('movementList');if(!list)return;if(!movements.length){list.innerHTML='<p class="empty-list">Todavía no hay movimientos registrados.</p>';return}list.innerHTML=movements.slice().reverse().map(m=>movementCard(m,movements.indexOf(m))).join('');bindRecordActions(list)}
function bindRecordActions(container){container.querySelectorAll('.edit-record').forEach(b=>b.addEventListener('click',()=>editMovement(Number(b.dataset.index))));container.querySelectorAll('.delete-record').forEach(b=>b.addEventListener('click',()=>deleteMovement(Number(b.dataset.index))))}
function persist(){localStorage.setItem('financial_totals_v1',JSON.stringify(totals));localStorage.setItem('financial_movements_v1',JSON.stringify(movements))}
function resetActive(){digits[activeType]='';$('activeAmount').value='';$('activeDate').value=today();$('activeCategory').value='';$('activeDescription').value='';$('activePerson').value='';$('activePayMonth').value='';editingIndex=null;$('saveActive').textContent=activeType==='income'?'Guardar ingreso':'Guardar gasto';updateConditionalFields()}
function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function saveMovement(){const amount=Number(digits[activeType]||0)/100,category=$('activeCategory').value,date=$('activeDate').value,description=$('activeDescription').value.trim(),person=$('activePerson').value.trim(),payMonth=$('activePayMonth').value;if(amount<=0)return toast(`Introduce un importe de ${activeType==='income'?'ingreso':'gasto'}`);if(!date)return toast('Selecciona una fecha');if(!category)return toast('Selecciona una categoría');if(descriptionCategories.includes(category)&&!description)return toast('Completa la descripción');if(personCategories.includes(category)&&!person)return toast('Indica la persona de este movimiento');if(category==='Nómina'&&!payMonth)return toast('Selecciona el mes de nómina');if(editingIndex!==null){const old=movements[editingIndex];totals[old.type]-=Number(old.amount);totals[activeType]+=amount;movements[editingIndex]={...old,type:activeType,amount,date,category,description,createdAt:old.createdAt||new Date().toISOString(),...(personCategories.includes(category)&&person?{person}:{}),...(category==='Nómina'&&payMonth?{payMonth}:{})};if(!personCategories.includes(category))delete movements[editingIndex].person;if(category!=='Nómina')delete movements[editingIndex].payMonth;toast('Registro actualizado')}else{totals[activeType]+=amount;movements.push({type:activeType,amount,date,category,description,createdAt:new Date().toISOString(),...(personCategories.includes(category)&&person?{person}:{}),...(category==='Nómina'&&payMonth?{payMonth}:{})});toast(activeType==='income'?'Ingreso guardado':'Gasto guardado')}persist();resetActive();updateReports();renderReportMovements();renderMovements()}
function editMovement(index){const m=movements[index];if(!m)return;editingIndex=index;activeType=m.type;switchType(m.type);digits[m.type]=String(Math.round(Number(m.amount)*100));renderAmount();$('activeDate').value=m.date||today();$('activeCategory').value=m.category||'';$('activeDescription').value=m.description||'';$('activePerson').value=m.person||'';$('activePayMonth').value=m.payMonth||'';updateConditionalFields();$('saveActive').textContent=m.type==='income'?'Actualizar ingreso':'Actualizar gasto';selectRegisterTab('register');toast('Editando registro')}
function deleteMovement(index){if(!movements[index])return;if(!confirm('¿Eliminar este registro?'))return;const m=movements[index];totals[m.type]-=Number(m.amount);if(totals[m.type]<0)totals[m.type]=0;movements.splice(index,1);persist();updateReports();renderReportMovements();renderMovements();toast('Registro eliminado')}
function updatePersonField(){const field=$('personField'),input=$('activePerson'),category=$('activeCategory')?.value,showPerson=personCategories.includes(category);if(!field||!input)return;field.classList.toggle('hidden',!showPerson);input.required=showPerson}
function updateDescriptionField(){const field=$('descriptionField'),input=$('activeDescription'),category=$('activeCategory')?.value,showDescription=descriptionCategories.includes(category);if(!field||!input)return;field.classList.toggle('hidden',!showDescription);input.required=showDescription}
function updatePayMonthField(){const field=$('payMonthField'),input=$('activePayMonth'),category=$('activeCategory')?.value,showMonth=activeType==='income'&&category==='Nómina';if(!field||!input)return;field.classList.toggle('hidden',!showMonth);input.required=showMonth}
function updateConditionalFields(){updatePersonField();updateDescriptionField();updatePayMonthField()}
function renderCategories(){const select=$('activeCategory');if(!select)return;select.innerHTML='<option value="">Selecciona una categoría</option>'+categories[activeType].map(c=>`<option>${c}</option>`).join('');updateConditionalFields()}
function switchType(type){activeType=type;const income=$('incomeTab'),expense=$('expenseTab');income.classList.toggle('active',type==='income');expense.classList.toggle('active',type==='expense');income.setAttribute('aria-selected',type==='income');expense.setAttribute('aria-selected',type==='expense');$('saveActive').textContent=editingIndex!==null?(type==='income'?'Actualizar ingreso':'Actualizar gasto'):(type==='income'?'Guardar ingreso':'Guardar gasto');renderCategories();renderAmount();if(editingIndex===null){$('activeDate').value=today();$('activeCategory').value='';$('activeDescription').value='';$('activePerson').value='';$('activePayMonth').value='';}updateConditionalFields()}
function applyTheme(mode){const dark=mode==='dark',html=document.documentElement;html.classList.toggle('theme-light',!dark);html.classList.toggle('theme-dark',dark);document.body.classList.toggle('theme-light',!dark);document.body.classList.toggle('theme-dark',dark);[['themeToggle','themeIcon'],['registerThemeToggle','registerThemeIcon'],['movementsThemeToggle','movementsThemeIcon']].forEach(([buttonId,iconId])=>{const button=$(buttonId),icon=$(iconId);if(button&&icon){icon.textContent=dark?'☀':'☾';button.setAttribute('aria-label',dark?'Cambiar a modo día':'Cambiar a modo noche');button.title=dark?'Modo día':'Modo noche'}});localStorage.setItem('theme_mode_v1',dark?'dark':'light')}

$('registerButton')?.addEventListener('click',()=>{editingIndex=null;selectRegisterTab('register')});
$('reportsButton')?.addEventListener('click',()=>{updateReports();renderReportMovements();show('reports')});
$('backButton')?.addEventListener('click',()=>{editingIndex=null;show('home')});
$('reportsBack')?.addEventListener('click',()=>show('home'));
$('formBack')?.addEventListener('click',()=>selectRegisterTab('register'));
document.querySelectorAll('.register-tab[data-tab="register"]').forEach(button=>button.addEventListener('click',()=>selectRegisterTab('register')));
document.querySelectorAll('.register-tab[data-tab="movements"]').forEach(button=>button.addEventListener('click',()=>selectRegisterTab('movements')));
$('movementsBack')?.addEventListener('click',()=>selectRegisterTab('register'));
$('saveActive')?.addEventListener('click',saveMovement);
$('incomeTab')?.addEventListener('click',()=>switchType('income'));
$('expenseTab')?.addEventListener('click',()=>switchType('expense'));
const toggleTheme=()=>applyTheme(document.documentElement.classList.contains('theme-dark')?'light':'dark');
$('themeToggle')?.addEventListener('click',toggleTheme);
$('registerThemeToggle')?.addEventListener('click',toggleTheme);
$('movementsThemeToggle')?.addEventListener('click',toggleTheme);
$('activeCategory')?.addEventListener('change',updateConditionalFields);
const input=$('activeAmount');input?.addEventListener('focus',()=>input.select());input?.addEventListener('input',e=>{digits[activeType]=e.target.value.replace(/[^0-9]/g,'').slice(0,10);renderAmount()});
$('activeDate').value=today();
$('sharedKeypad')?.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.key;if(k==='clear')digits[activeType]='';else if(k==='backspace')digits[activeType]=digits[activeType].slice(0,-1);else if(digits[activeType].length<10)digits[activeType]+=k;renderAmount()}));
const savedTheme=localStorage.getItem('theme_mode_v1');applyTheme(savedTheme==='dark'||savedTheme==='light'?savedTheme:'light');renderCategories();renderReportMovements();show('home');if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand()}
