const tg = window.Telegram?.WebApp;
const STORAGE_KEY = 'financial_movements_v1';
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor('#0b3d91'); tg.setBackgroundColor('#ffffff'); }
const menu = document.getElementById('menu');
const notify = (message) => tg?.showAlert ? tg.showAlert(message) : alert(message);
const getMovements = () => { try { const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'); return Array.isArray(data)?data:[]; } catch { return []; } };
const saveMovements = (movements) => localStorage.setItem(STORAGE_KEY,JSON.stringify(movements));
const formatMoney = (value) => new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(value);
const formatDate = (value) => { if(!value)return ''; const [year,month,day]=value.split('-'); return `${day}/${month}/${year}`; };
const escapeHtml = (value) => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const renderSummary = () => { const movements=getMovements(); const income=movements.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0); const expense=movements.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0); return `<section class="summary"><div class="summary-card"><small>Ingresos</small><strong>${formatMoney(income)}</strong></div><div class="summary-card"><small>Gastos</small><strong>${formatMoney(expense)}</strong></div><div class="summary-card summary-balance"><small>Saldo</small><strong>${formatMoney(income-expense)}</strong></div></section>`; };
const renderMovementList = () => { const movements=getMovements().sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`)); if(!movements.length)return '<section class="movements"><div class="empty-state">Aún no hay movimientos registrados.</div></section>'; return `<section class="movements"><div class="section-title"><h2>Movimientos</h2><span>${movements.length}</span></div><div class="movement-list">${movements.map(m=>`<article class="movement-item"><div class="movement-icon ${m.type}">${m.type==='income'?'+':'−'}</div><div class="movement-info"><strong>${escapeHtml(m.category)}</strong><small>${formatDate(m.date)}${m.description?` · ${escapeHtml(m.description)}`:''}</small></div><div class="movement-amount ${m.type}">${m.type==='income'?'+':'−'}${formatMoney(m.amount)}</div></article>`).join('')}</div></section>`; };
const renderMovementMenu = () => { menu.innerHTML=`<button class="back-button" id="back-home" type="button"><span>‹</span> Atrás</button>${renderSummary()}<section class="movement-actions"><button class="action-tile income-tile" id="income" type="button"><span class="tile-icon">＋</span><strong>Ingreso</strong><small>Registrar dinero recibido</small></button><button class="action-tile expense-tile" id="expense" type="button"><span class="tile-icon">−</span><strong>Gastos</strong><small>Registrar dinero gastado</small></button></section>${renderMovementList()}`; document.getElementById('back-home').addEventListener('click',renderHome); document.getElementById('income').addEventListener('click',()=>renderForm('income')); document.getElementById('expense').addEventListener('click',()=>renderForm('expense')); };
const renderForm = (type) => {
  const isIncome=type==='income'; const categories=isIncome?['Nómina','Freelance','Ventas','Inversiones','Otros']:['Vivienda','Alimentación','Transporte','Salud','Ocio','Compras','Servicios','Otros'];
  menu.innerHTML=`<button class="back-button" id="back-movements" type="button"><span>‹</span> Atrás</button><section class="form-card ${type}-form"><div class="form-heading"><div class="form-icon ${type}">${isIncome?'+':'−'}</div><div><p class="eyebrow-dark">NUEVO MOVIMIENTO</p><h2>${isIncome?'Registrar ingreso':'Registrar gasto'}</h2></div></div><form id="movement-form"><div class="amount-field"><label for="amount">IMPORTE</label><div class="amount-display"><span>€</span><strong id="amount-value">0,00</strong></div><input id="amount" name="amount" type="hidden" value=""><small>Toca los números para introducir el importe</small><div class="numeric-keypad" aria-label="Teclado numérico"><button type="button" data-key="1">1</button><button type="button" data-key="2">2</button><button type="button" data-key="3">3</button><button type="button" data-key="4">4</button><button type="button" data-key="5">5</button><button type="button" data-key="6">6</button><button type="button" data-key="7">7</button><button type="button" data-key="8">8</button><button type="button" data-key="9">9</button><button type="button" data-key="clear">C</button><button type="button" data-key="0">0</button><button type="button" data-key="backspace">⌫</button></div></div><div class="form-grid"><label>Fecha<input id="date" name="date" type="date" required></label><label>Categoría<select id="category" name="category" required><option value="" selected disabled>Selecciona una categoría</option>${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select></label></div><label>Descripción <span>opcional</span><textarea id="description" name="description" rows="3" maxlength="160" placeholder="Añade una descripción"></textarea></label><button class="primary-button ${type}" type="submit">Guardar movimiento</button></form></section>`;
  const amountInput=document.getElementById('amount'); const amountValue=document.getElementById('amount-value'); let raw='';
  const updateAmount=()=>{ const numeric=Number(raw||0)/100; amountValue.textContent=numeric.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}); amountInput.value=raw?String(numeric):''; };
  document.querySelectorAll('.numeric-keypad button').forEach(button=>button.addEventListener('click',()=>{ const key=button.dataset.key; if(key==='clear')raw=''; else if(key==='backspace')raw=raw.slice(0,-1); else if(raw.length<9)raw+=key; updateAmount(); }));
  document.getElementById('date').value=new Date().toISOString().slice(0,10); document.getElementById('back-movements').addEventListener('click',renderMovementMenu);
  document.getElementById('movement-form').addEventListener('submit',(event)=>{event.preventDefault(); const form=new FormData(event.currentTarget); const amount=Number(raw)/100; const date=String(form.get('date')||''); const category=String(form.get('category')||''); const description=String(form.get('description')||'').trim(); if(!Number.isFinite(amount)||amount<=0||!date||!category){notify('Completa el importe, la fecha y la categoría con valores válidos.');return;} const movements=getMovements(); movements.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,type,amount:Math.round(amount*100)/100,date,category,description,createdAt:new Date().toISOString()}); saveMovements(movements); renderMovementMenu(); notify(`${isIncome?'Ingreso':'Gasto'} guardado correctamente.`);});
};
const renderHome=()=>{menu.innerHTML=`<button class="menu-card" id="gastos" type="button"><span class="icon">↕</span><span class="card-text"><strong>Control de gastos</strong><small>Registra y organiza tus movimientos</small></span><span class="arrow">›</span></button><button class="menu-card" id="informes" type="button"><span class="icon">▥</span><span class="card-text"><strong>Informes</strong><small>Consulta el resumen de tus finanzas</small></span><span class="arrow">›</span></button>`; bindHomeEvents();};
const bindHomeEvents=()=>{document.getElementById('gastos').addEventListener('click',renderMovementMenu);document.getElementById('informes').addEventListener('click',()=>notify('Informes: módulo preparado para la siguiente fase.'));};
bindHomeEvents();
